name: docker hub

on:
  workflow_dispatch:

jobs:
  pull and run:
    runs-on: ubuntu-latest

    steps:
      - name: Pull docker image
        run: docker pull artur9022/goapp
        
      - name: Run docker image
        run: docker run artur9022/goapp