name: Release to Docker Hub

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
#     - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Build the docker image
        run: docker build -t kotiaara/go .  

      - name: Conteiner
        run: docker run -d kotiaara/go

      - name: Build and push Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kotiaara/go
          tags: latest, ${{ github.run_number }}
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
