name: matrix hello

on:
  workflow_dispatch:

jobs:
  matrix_go:
    strategy:
      matrix:
        ubuntu_version: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        go_versions: [1.18,1.19.1,1.19.2]
    runs-on: ${{ matrix.ubuntu_version }}

    steps:
      - name: Install go
        uses: action/setup-go@v3
        with:
          node-version: ${{ matrix.go_version }}

      - uses: action/checkout@v3

      - name: Go
        run: go run main.go     

